### ISSUE TITLE
403 Forbidden for static files

### ISSUE THREAD

**Issue by draft1** [jeffmvr/mangle-vpn#1]
I tried on Ubuntu 18 and Debian 9, both web panel is not working.
All static files return 403 Forbidden.

Thanks!

**Comment by jeffmvr** [comment]
This usually happens when the install script was not run as root (or via sudo) or if SELinux is enabled. Can you verify ownership and permissions on the /opt/mangle-vpn folder via:

`$ ls -l /opt/mangle-vpn`

All files, specifically in the ui/ directory, should be owner be root.

--jeff

**Comment by draft1** [comment]
I'm using DigitalOcean by the way.

> This usually happens when the install script was not run as root (or via sudo)

It is run as root.

> if SELinux is enabled.

So I should manually disable Selinux first?
But seems selinux is not present/enabled on Ubuntu 18.04.

> Can you verify ownership and permissions on the /opt/mangle-vpn folder via:

ls -l /opt/mangle-vpn
ls: cannot access '/opt/mangle-vpn': No such file or directory

**Comment by draft1** [comment]
I guess you mean?
/root/mangle-vpn/ui/public/static 

ls -l /root/mangle-vpn/
total 76
-rw-r--r-- 1 root root 35148 Jun 10 19:53 LICENSE
-rw-r--r-- 1 root root   425 Jun 10 19:53 Makefile
-rw-r--r-- 1 root root  4195 Jun 10 19:53 README.md
drwxr-xr-x 5 root root  4096 Jun 10 19:57 data
-rwxr-xr-x 1 root root  2398 Jun 10 19:53 install.sh
-rwxr-xr-x 1 root root   680 Jun 10 19:53 manage.py
drwxr-xr-x 6 root root  4096 Jun 10 19:54 mangle
-rw-r--r-- 1 root root   575 Jun 10 19:53 requirements.txt
drwxr-xr-x 2 root root  4096 Jun 10 19:53 scripts
drwxr-xr-x 7 root root  4096 Jun 10 19:53 ui

All owned by root.

**Comment by draft1** [comment]
Works fine now when I install it under **/opt/** folder.
This should be added on the guide/read me notes.

Thanks a lot!

**Comment by jeffmvr** [comment]
Thanks for the feedback, I will def add that to the documentation! I remember having an issue when installing it in the /root directory but sadly I don't remember the exact issue.

Let me know if you have any other issues.

--jeff
